spring:
  application:
    name: Plus

  datasource:
    url: jdbc:mysql://localhost:3306/plus #테이블 명 변경 하기
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update        # 테이블 자동 생성/업데이트 (실무는 validate, none)
    show-sql: true             # 실행되는 SQL 로그 보기
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: info

jwt:
  secret:
    key: L6h/xMxGO53HQmR/OB99qR/y0kTr2CAyaI5RqBIX184=


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name:my-app}
    enable:
      tomcat: true